### ISSUE TITLE
runtime upgrade for faucet and reputation-commitments

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#190]
* [x] try-runtime migration against Kusama mainnet (1.5.0 collator running on: wss://encointer.api.onfinality.io/public-ws)
* [x] benchmarks
* [x] test on rococo: runtime v15 1.5.0 release
   * [x] test teleport from relaychain
   * [x] test faucet
   * [x] test bazaar: rpc get fails, likely outdated rpc client binary
   * [x] test app 1.10.4+867: communities are listed and balance is correct
   * [x] test explorer: it works in spite of breaking metadata change
* [x] deploy on kusama, in batch with asset hub 1.0.0 upgrade

if possible, polkadot-v1.0.0 deps
* [ ] benchmark again

**Comment by brenzi** [comment]
enactAuthorized Upgrade on rococo has happened:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.encointer.org#/explorer/query/0xe53f8c89fd93298986faf7baaeb93037571058f9f21bce4c4b39831b10c831d9

**Comment by brenzi** [comment]
faucet testing:
the reserve amount is 0 and currently only root can change that. we should let council define this

creation:
![image.png](https://images.zenhubusercontent.com/5c8abd48181dc00205770dc3/7478d188-9ff9-4e06-918d-794e4e86fa77)

![image.png](https://images.zenhubusercontent.com/5c8abd48181dc00205770dc3/f385f364-18f1-448f-a65a-ecb549077370)

```
encointerFaucet.faucets: Option<EncointerPrimitivesFaucet>
[
  [
    [
      JAMgeGvbUhsf9LoneEB3SCgEbjzUSisX25tz636x8Djv1W6
    ]
    {
      name: TestRocFaucet
      purposeId: 0
      whitelist: [
        {
          geohash: srcq4
          digest: 0xabb12168
        }
      ]
      dripAmount: 100,000,000,000
      creator: Er6zYnUBUdhEtb7dpfMMUq9PtSwUSzN9vhxT7B42qugeLhc
    }
  ]
]
```

**Comment by brenzi** [comment]
when I try to get a list of all communities with the cli, the rpc fails:
```
nctr-r list-communities
thread 'main' panicked at 'No communities returned. Are you running the node with `--enable-offchain-indexing true`?: Client(ParseError(Error("invalid type: string \"Adriana\", expected a sequence", line: 0, column: 0)))', client/src/main.rs:2268:72
```

the rpc endpoint is running client v1.3.3. maybe that's the reason? the rpc cache actually doesn't cache CommunityMetadata, only cid, which saw no breaking change

**Comment by brenzi** [comment]
when I try to get a list of all communities with the cli, the rpc fails:
```
nctr-r list-communities
thread 'main' panicked at 'No communities returned. Are you running the node with `--enable-offchain-indexing true`?: Client(ParseError(Error("invalid type: string \"Adriana\", expected a sequence", line: 0, column: 0)))', client/src/main.rs:2268:72
```

the rpc endpoint is running client v1.3.3. maybe that's the reason? the rpc cache actually doesn't cache CommunityMetadata, only cid, which saw no breaking change

**Comment by brenzi** [comment]
testing bazaar:
`./bazaar.py -r rococo --cid srcq45PYNyD --bizaccount //Alice register-business ~/tmp/biz.json`
yields
```
encointerBazaar.businessRegistry: EncointerPrimitivesBazaarBusinessData
[
  [
    [
      {
        geohash: srcq4
        digest: 0xabb12168
      }
      HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F
    ]
    {
      url: QmTTHFZ7roMRZD619Tn8mAttAmn2CnAh8NUXR4VocRvcfh
      lastOid: 1
    }
  ]
]
```
